/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 demon.glb -T -S
Author: OliviaGene (https://sketchfab.com/Oliviagene)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aov-violet-demonic-morphed-07c72dc748eb46afbb5cf9c5cb2aea75
Title: (AOV) Violet: Demonic Morphed
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Demon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/demon-transformed.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Idleshow"].play();
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[0, 0, 0]}
      position={[0, -7.5, 2]}
      scale={5}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={105.22}
        >
          <group
            name="11114_SunShangXiang_Show3fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="11114_SunShangXiang_Show3">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={
                        materials["11114_SunShangXiangCrystal_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials["11114_SunShangXiang_ShowHigh"]}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials["11114_SunShangXiang_ShowHigh"]}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                      name="Object_14"
                      geometry={nodes.Object_14.geometry}
                      material={materials["11114_SunShangXiangFace_ShowHigh"]}
                      skeleton={nodes.Object_14.skeleton}
                    />
                    <skinnedMesh
                      name="Object_16"
                      geometry={nodes.Object_16.geometry}
                      material={materials["11114_SunShangXiangHair_ShowHigh"]}
                      skeleton={nodes.Object_16.skeleton}
                    />
                    <skinnedMesh
                      name="Object_18"
                      geometry={nodes.Object_18.geometry}
                      material={
                        materials["11114_SunShangXiangCrystal_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_18.skeleton}
                    />
                    <skinnedMesh
                      name="Object_20"
                      geometry={nodes.Object_20.geometry}
                      material={
                        materials["11114_SunShangXiangCrystal_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_20.skeleton}
                    />
                    <skinnedMesh
                      name="Object_22"
                      geometry={nodes.Object_22.geometry}
                      material={materials["11114_SunShangXiang_ShowHigh"]}
                      skeleton={nodes.Object_22.skeleton}
                    />
                    <skinnedMesh
                      name="Object_24"
                      geometry={nodes.Object_24.geometry}
                      material={
                        materials["11114_SunShangXiangWeapon_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_24.skeleton}
                    />
                    <skinnedMesh
                      name="Object_26"
                      geometry={nodes.Object_26.geometry}
                      material={
                        materials["11114_SunShangXiangWeapon_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_26.skeleton}
                    />
                    <skinnedMesh
                      name="Object_28"
                      geometry={nodes.Object_28.geometry}
                      material={
                        materials["11114_SunShangXiangWeapon_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_28.skeleton}
                    />
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={
                        materials["11114_SunShangXiangWeapon_ShowVeryHigh"]
                      }
                      skeleton={nodes.Object_30.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/demon-transformed.glb");
